.github/workflows/release.yaml
We do not have a CI workflow that will auto-release the charm to charmhub upon a push to the main branch. We have acquired a charmhub token from the openstack team that will allow us to publish the charm to [mysql-router](https://charmhub.io/mysql-router) on the `dpe` track.
Add a CI workflow to auto-release the charm to the `dpe/edge` channel upon a push to the main branch
Add CI workflow to release to charmhub on push to main
=> Add CI workflow to release to charmhub on push to main

.github/workflows/ci.yaml, metadata.yaml
1. The name of the charm is `mysqlrouter` and thus cannot be uploaded to `mysql-router` on charmhub
2. The workflows in `ci.yaml` gets run upon push to main. The jobs in this workflow are duplicated in `release.yaml`
1. Change the name of the charm to `mysql-router`
2. Remove the duplicate workflow jobs from `ci.yaml`
Change name of charm to correctly upload to charmhub
=> Change name of charm to correctly upload to charmhub

.github/workflows/ci.yaml, .github/workflows/release.yaml, src/relations/database_requires.py, tests/integration/test_database.py
Currently, relations must formed in a specific order (the relation between `application<->mysqlrouter` first, and then the relation between `mysqlrouter<->mysql`). If we form the relations in reverse order, we miss the `backend-database-joined` event (which is where the database+user creation is requested).
Add an event handler for the `backend-database-joined` event where we will defer until the relation with the application (provides relation) is formed, after which we can safely request the database+user creation (by calling the event handler in data-platform-libs explicitly).
Allow for relations to be formed in any order
=> Allow for relations to be formed in any order

.github/workflows/ci.yaml, .github/workflows/release.yaml
1. We are running heavy integration tests even if the lighter ones (like linting and unit tests) fail
2. We are repeating CI workflows in `ci.yaml` and `release.yaml`
1. Introduce dependencies to only run the heavier CI workflows after the lighter ones finish successfully
2. Import CI workflows from `ci.yaml` into `release.yaml`
Add CI workflow dependency + import integration test CI workflows
=> Add CI workflow dependency + import integration test CI workflows

charmcraft.yaml, metadata.yaml, src/mysql_router_helpers.py, tests/integration/application-charm/metadata.yaml, tests/integration/application-charm/src/charm.py, tests/integration/test_database.py
We are not escaping database identifiers (like usernames, hostnames and databases) when creating a user in mysqlrouter. This is leading to a misleading error surfaced in [this jira ticket](https://warthogs.atlassian.net/browse/DPE-909).
Escape identifiers with backticks.
Escape database identifiers with backticks
=> Escape database identifiers with backticks

.github/workflows/ci.yaml, src/charm.py, src/mysql_router_helpers.py, tests/unit/test_charm.py, tests/unit/test_mysql_router_helpers.py, tox.ini
* [DPE-913](https://warthogs.atlassian.net/browse/DPE-913)
* Group Replication notifications are disabled
* Enable GR notifications config when bootstrapping mysql-router
* Added gr notification config flag to the bootstrap call
* Add handler for upgrade charm handler to reconfigure an already running charm
* Updated github checkout action version
* Enable Group Replication notifications
* Added unit tests for `_on_upgrade_charm`
* Added unit tests for `bootstrap_and_start_mysql_router`
=> Enable GR notifications

.github/workflows/ci.yaml, .github/workflows/release.yaml, .gitignore, charmcraft.yaml, tox.ini
The operator was not updated in store for a long:
https://charmhub.io/mysql-router?channel=dpe/edge (last update Nov 25, 2022)
While several important commits are available in git for publishing.
We have to disable charmcraft destructive mode to build focal on jammy GH runners.
While we are here, let's update all known dependencies and pinning to be up-2-date.
=> Disable charmcraft destructive mode, bump versions, add CodeCov

.github/workflows/release.yaml
The previous commit a06334465 had a [typo](https://github.com/canonical/mysql-router-operator/blob/a06334465a7b17e3f1672b49d5381c0da4f4f881/.github/workflows/release.yaml#L27) which makes GItHub sad:
```
Error: .github#L1
every step must define a `uses` or `run` key
```
Removing unnecessary line.
=> Remove leftover line from release.yaml to make GH CI/CD happy

src/charm.py, src/constants.py, src/mysql_router_helpers.py, tests/unit/test_charm.py, tests/unit/test_mysql_router_helpers.py
[dpe-1366](https://warthogs.atlassian.net/browse/DPE-1366), [issue 20](https://github.com/canonical/mysql-router-operator/issues/20)
Even though the mysql socket file has 777 permissions, the socket's parent directory has 700 which results in restricted access to the socket file by other users.
```
ubuntu@juju-a99e94-5:~$ sudo ls -la /var/lib/mysql/slurmdbd/                                          
total 40
drwx------ 5 mysql mysql 4096 Mar 16 15:31 .
drwxr-xr-x 3 mysql mysql 4096 Mar 16 15:31 ..
drwx------ 2 mysql mysql 4096 Mar 16 15:31 data
drwx------ 2 mysql mysql 4096 Mar 16 15:31 log
srwxrwxrwx 1 mysql mysql    0 Mar 16 15:31 mysql.sock
srwxrwxrwx 1 mysql mysql    0 Mar 16 15:31 mysqlro.sock
-rw------- 1 mysql mysql 2358 Mar 16 15:31 mysqlrouter.conf
-rw------- 1 mysql mysql   94 …
```
=> Fix mysqlrouter application directory permissions to enable access to socket file from other users

tests/integration/test_tls.py, tox.ini
We are not supporting TLS on socket connection (since it does not add any extra security).
But we still need to prove there's encryption on connection when using the router.
Hence this test.
Unblocks [DPE-1309](https://warthogs.atlassian.net/browse/DPE-1309)
[DPE-1309]: https://warthogs.atlassian.net/browse/DPE-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add test to ensure encryption

lib/charms/data_platform_libs/v0/data_interfaces.py, src/snap.py
We have built a new snap for charmed-mysql with v8.0.34. The snap installed by the charm is outdated
Update the snap revision
=> DPE-2427 Update charm to use charmed-mysql snap rev 69 (v8.0.34)

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/operator_libs_linux/v2/snap.py, metadata.yaml
* documentation on Discourse was missing
* metadata.yaml was outdated (missing lings, outdated year, wrong summary, etc)
We are preparing the charm for release to stable and need to
generate all the necessary documentation/links on https://charmhub.io/mysql-router
* update metadata.yaml to match mysql-router-k8s concepts
* add Discourse documentation Overview page
=> DPE-2752 Add Discourse documentation + update metadata.yaml

src/machine_workload.py, src/upgrade.py, src/workload.py
During the lastest feature merge, we misconfigured some kwargs to various methods
Fix misconfigured kwargs
=> [DPE-4219] Fix missing kwargs in some methods

.github/workflows/ci.yaml, actions.yaml, src/machine_workload.py, src/snap.py, src/upgrade.py, src/workload.py, tests/integration/conftest.py, tests/integration/helpers.py, tests/integration/juju_.py, tests/integration/test_upgrade.py
We do not have integration tests for upgrade
Add integration tests
=> [DPE-4179, DPE-4219] Add integration test for upgrades

.github/workflows/ci.yaml, charmcraft.yaml, config.yaml, lib/charms/tempo_k8s/v2/tracing.py, metadata.yaml, poetry.lock, src/abstract_charm.py, src/machine_charm.py, src/relations/database_providers_wrapper.py, src/relations/database_provides.py, src/relations/hacluster.py, tests/integration/helpers.py, tests/integration/test_data_integrator.py, tests/integration/test_hacluster.py
We need to add integration support for the hacluster charm. This will allow the mysqlrouter charm to be exposed via data-integrator through a provided virtual IP
Add integration support
=> [DPE-5249] Add integration support for hacluster

lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tempo_coordinator_k8s/v0/tracing.py, pyproject.toml, src/abstract_charm.py, src/machine_charm.py, tests/unit/conftest.py
We are unable to relay traces through grafana-agent due to https://github.com/canonical/grafana-agent-operator/issues/195. However, in the meantime, we would like to update the charm tracing libs as they now reside in `tempo_coordinator_k8s`
Update location of charm tracing libs
=> [DPE-5312] Pull tracing charm libs from tempo_coordinator_k8s instead

.github/workflows/ci.yaml
We are not running tests on juju 3.6/*
Run tests against juju 3.6/candidate on a nightly schedule
=> Update 3.6 nightly tests to run against 3.6/candidate instead of 3.6/beta

src/machine_charm.py, src/workload.py
This PR adds warning level messages when a _destructive_ action is performed. The definition of _destructive_ seems to be associated with data loss, which I think it can only happen, from user action, whenever they force an upgrade when the charm has already detected its lack of compatibility.
- Paulo confirmed that this ticket was created to familiarised myself with the codebases.
- Alex referenced this PostgreSQL operator [PR](https://github.com/canonical/postgresql-k8s-operator/pull/753) as the reason behind the need for warnings.
=> [DPE-5711] Add warnings to destructive actions

src/architecture.py, src/machine_charm.py, tests/conftest.py, tests/integration/helpers.py, tests/integration/test_architecture.py, tests/unit/test_architecture.py
This PR introduces the usage of the newly created architecture module, similar to the one in the MySQL lib (see [code](https://github.com/canonical/mysql-operator/blob/main/lib/charms/mysql/v0/architecture.py)).
The shape of the integration tests, as well as the helper used to get the built charm in the architecture that mismatches the one of the host itself, have been adapted from the one Lucas created for PostgreSQL-k8s (see [code](https://github.com/canonical/postgresql-k8s-operator/blob/70a96ce33eb0de054b9297e3bd558f6ece54c0b0/tests/integration/test_wrong_arch.py)).
- The new logic has been added as a module, and not as a charm lib, due to @carlcsaposs-canonical preference.
- The integration test fixtures have been defined in `conftest.py` and not in `markers.py` to respect the …
=> [DPE-5588] Check against invalid arch

src/container.py, src/mysql_shell/__init__.py, src/mysql_shell/templates/try_except_wrapper.py.jinja
We are storing passwords on disk (in the mysqlsh python script) when we execute mysqlsh. This is a security vulnerability
Avoid writing passwords on disk, and instead use `--passwords-from-stdin` flag of mysqlsh
=> [DPE-6447] Avoid storing passwords on disk when running mysqlsh

.github/workflows/integration_test.yaml, charmcraft.yaml, spread.yaml
This PR temporarily removes `ubuntu20` base, as it currently fails to build due to [this problem](https://github.com/canonical/charmcraft/issues/2259), and is blocking PRs:
- https://github.com/canonical/mysql-router-operator/pull/241.
- https://github.com/canonical/mysql-router-operator/pull/249.
=> [MISC] Remove ubuntu@20.04 base

tests/integration/test_exporter.py, tests/integration/test_exporter_with_tls.py
The Observability team removed the `latest/stable` track as of Friday June 20. Channels will now be prefixed by the charm major versions (i.e. `1/...`, `2/...`). See:
- June 20th: Last [CI run](https://github.com/canonical/mysql-router-operator/actions/runs/15769090923) where exporter integration tests passed.
- June 21th: First [CI run](https://github.com/canonical/mysql-router-operator/actions/runs/15790569479) where exporter integration tests failed.
=> [MISC] Pin grafana-agent channel to `1/stable`
